language: python
sudo: false
dist: xenial
os: linux

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8-dev
          env: TOXENV=py38
        - python: 3.5
          env: TOXENV=flake8

install:
  - pip install -r requirements.d/development.txt
  - pip install .

script: tox moin
