application: moin2-test
version: dev
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  MOINCFG: ../wikiconfig_gae.py

handlers:
- url: /.*
  script: MoinMoin.appengine_main.application

libraries:
- name: jinja2
  version: latest

