#!/bin/bash
# create a virtual environment in directory env/
virtualenv --no-site-packages env
source env/bin/activate

download()
{
    if test -x /usr/bin/curl
    then
        echo /usr/bin/curl -L -o $1 $2
        /usr/bin/curl -L -o $1 $2
    else
        echo wget -nc -O $1 $2
        wget -nc -O $1 $2
    fi
}

# get some 3rd party stuff and unpack them into env/, where the default
# wikiconfig.py expects them. should be replaced by packaging.
# we do this FIRST, so that breakage with pip install is better visible.

URL=http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.5/ckeditor_3.5.tar.gz
download env/ckeditor.tgz $URL 
tar xz -C env/ -f env/ckeditor.tgz

URL=http://static.moinmo.in/files/packages/TWikiDrawPlugin-moin.tar.gz
download env/twd.tgz $URL
tar xz -C env/ -f env/twd.tgz

URL=http://static.moinmo.in/files/packages/svg-edit.tar.gz
download env/svgedit.tgz $URL
tar xz -C env/ -f env/svgedit.tgz

URL=http://code.jquery.com/jquery-1.4.4.min.js
mkdir env/jquery
download env/jquery/jquery.min.js $URL

URL=http://svgweb.googlecode.com/files/svgweb-2010-08-10-Owlephant-1.zip
download env/svgweb.zip $URL
unzip -q -o -d env/ env/svgweb.zip

URL='http://downloads.sourceforge.net/project/anywikidraw/anywikidraw/anywikidraw-0.14/anywikidraw-0.14.zip?use_mirror=ignum'
DIR='AnyWikiDraw 0.14'
download env/awd.zip $URL
unzip -q -o -d env/ env/awd.zip
cd env/
ln -s "$DIR" AnyWikiDraw
cd ..

# first install babel, moin's setup.py will emit a warning if it is not there
pip install babel

# "install" moin2 from repo to the env, this will also install required python
# packages from pypi. we do this LAST, so that breakage is better visible.
pip install -e .

# compile the translations
python setup.py compile_catalog --statistics

