# Copyright: 2023 MoinMoin project
# License: GNU GPL v2 (or any later version), see LICENSE.txt for details.

"""
MoinMoin - Scrapy project settings for moincrawler.

Scrapy settings for the moincrawler project, generated by ``scrapy startproject``.

For simplicity, this file contains only settings considered important or commonly used.
For more settings, consult the documentation:
    https://docs.scrapy.org/en/latest/topics/settings.html
    https://docs.scrapy.org/en/latest/topics/downloader-middleware.html
    https://docs.scrapy.org/en/latest/topics/spider-middleware.html
"""

BOT_NAME = "moincrawler"

SPIDER_MODULES = ["moin.cli._tests.scrapy.moincrawler.spiders"]
NEWSPIDER_MODULE = "moin.cli._tests.scrapy.moincrawler.spiders"
# Obey robots.txt rules
ROBOTSTXT_OBEY = True
