# Copyright: 2026 MoinMoin:UlrichB
# License: GNU GPL v2 (or any later version), see LICENSE.txt for details.

from moin import log
from markupsafe import Markup

logging = log.getLogger(__name__)


def safe_markup(html: str | Markup) -> Markup:
    """
    Mark already escaped HTML elements as safe for Jinja rendering.

    This function should only be used with HTML generated by Moins renderers,
    where all user content has been escaped before being combined with fixed markup.
    This is not a sanitizer and does not validate arbitrary HTML elements.

    :param html: A string containing pre-escaped HTML
    :return: A markupsafe.Markup instance suitable for Jinja rendering
    """

    if isinstance(html, Markup):
        return html

    if not isinstance(html, str):
        raise TypeError("safe_markup expects str or Markup")

    # simple checks as a last resort
    lowered = html.lower()
    for critical in ("<script", "javascript:"):
        if critical in lowered:
            logging.warning(f"Forbidden HTML tag '{critical}' detected\n{html[:132]}")

    return Markup(html)  # nosec B704
